version: build-{build}.{branch}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: NuGet
